version: "3.7"

services:
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: graphQl
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kukduku-server
    container_name: kukduku-node-server
    command: npm start
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kukduku-client
    container_name: kukduku-react-client
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  web-root:
    driver: local
